#######################################################################
# Kubernetes StatefulSet for Wazuh manager worker nodes
#
# We deploy two replicas here and we set a Pod anti-affinity policy to
# make sure the master and worker pods are not all running on the same
# Kubernetes node.
#######################################################################

apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: wazuh-manager-worker-1
  namespace: wazuh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wazuh-manager
      wazuh-manager-role: worker-1
  serviceName: wazuh-cluster
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: wazuh-manager
        wazuh-manager-role: worker-1
      name: wazuh-manager-worker-1
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: wazuh-manager-role
                      operator: In
                      values:
                        - master
                topologyKey: kubernetes.io/hostname
      volumes:
        - name: config
          configMap:
            name: wazuh-manager-worker-1-conf
      containers:
        - name: wazuh-manager
          image: 'wazuh/wazuh:3.6.1_6.4.0'
          resources:
            requests:
              cpu: 500m
              memory: 256Mi
            limits:
              cpu: 1
              memory: 512Mi
          volumeMounts:
            - name: config
              mountPath: /wazuh-config-mount/etc/ossec.conf
              subPath: ossec.conf
              readOnly: true
            - name: wazuh-manager-worker
              mountPath: /var/ossec/data
            - name: wazuh-manager-worker
              mountPath: /etc/postfix
          ports:
            - containerPort: 1514
            - containerPort: 1515
            - containerPort: 1516
            - containerPort: 55000
  volumeClaimTemplates:
    - metadata:
        name: wazuh-manager-worker
        namespace: wazuh
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: gp2-encrypted-retained
        resources:
          requests:
            storage: 10Gi
