#######################################################################
# ConfigMap to easily change values in the ossec.conf file without
# having to create a custom Docker image
#######################################################################

apiVersion: v1
kind: ConfigMap
metadata:
  name: wazuh-agent-ossec-conf
  namespace: wazuh
data:
  # /var/ossec/etc-template/ossec.conf
  ossec.conf: |-
    <!--
      Wazuh - Agent - Default configuration for ubuntu 18.10
      More info at: https://documentation.wazuh.com
      Mailing list: https://groups.google.com/forum/#!forum/wazuh
    -->

    <ossec_config>
      <client>
        <server>
          <address>wazuh-manager</address>
          <port>1514</port>
          <protocol>tcp</protocol>
        </server>
        <config-profile>ubuntu, ubuntu18, ubuntu18.10</config-profile>
        <notify_time>60</notify_time>
        <time-reconnect>300</time-reconnect>
        <auto_restart>yes</auto_restart>
      </client>

      <client_buffer>
        <!-- Agent buffer options -->
        <disabled>no</disabled>
        <queue_size>5000</queue_size>
        <events_per_second>500</events_per_second>
      </client_buffer>

      <!-- Policy monitoring -->
      <rootcheck>
        <disabled>no</disabled>
        <check_unixaudit>yes</check_unixaudit>
        <check_files>yes</check_files>
        <check_trojans>yes</check_trojans>
        <check_dev>yes</check_dev>
        <check_sys>yes</check_sys>
        <check_pids>yes</check_pids>
        <check_ports>yes</check_ports>
        <check_if>yes</check_if>

        <!-- Frequency that rootcheck is executed - every 12 hours -->
        <frequency>43200</frequency>

        <rootkit_files>/var/ossec/etc/shared/rootkit_files.txt</rootkit_files>
        <rootkit_trojans>/var/ossec/etc/shared/rootkit_trojans.txt</rootkit_trojans>

        <system_audit>/var/ossec/etc/shared/system_audit_rcl.txt</system_audit>
        <system_audit>/var/ossec/etc/shared/system_audit_ssh.txt</system_audit>
        <system_audit>/var/ossec/etc/shared/cis_debian_linux_rcl.txt</system_audit>

        <skip_nfs>yes</skip_nfs>
      </rootcheck>

      <wodle name="open-scap">
        <disabled>yes</disabled>
        <timeout>1800</timeout>
        <interval>1d</interval>
        <scan-on-start>yes</scan-on-start>
      </wodle>

      <wodle name="cis-cat">
        <disabled>yes</disabled>
        <timeout>1800</timeout>
        <interval>1d</interval>
        <scan-on-start>yes</scan-on-start>

        <java_path>wodles/java</java_path>
        <ciscat_path>wodles/ciscat</ciscat_path>
      </wodle>

      <!-- File integrity monitoring -->
      <syscheck>
        <disabled>no</disabled>

        <auto_ignore>no</auto_ignore>

        <!-- Frequency that syscheck is executed default every 12 hours -->
        <frequency>43200</frequency>

        <!-- This option specifies whether syscheck will ignore files that change too often (more than 3 changes). -->
        <scan_on_start>yes</scan_on_start>

        <!-- Directories to check  (perform all possible verifications) -->
        <directories check_all="yes">/etc,/usr/bin,/usr/sbin</directories>
        <directories check_all="yes">/bin,/sbin,/boot</directories>

        <!-- Directories to check in the mounted path from the docker container  (perform all possible verifications) -->
        <directories check_all="yes">/opt/hostexport/etc,/opt/hostexport/usr/bin,/opt/hostexport/usr/sbin</directories>
        <directories check_all="yes">/opt/hostexport/bin,/opt/hostexport/sbin,/opt/hostexport/boot</directories>

        <alert_new_files>yes</alert_new_files>

        <!-- Files/directories to ignore -->
        <ignore>/etc/mtab</ignore>
        <ignore>/etc/hosts.deny</ignore>
        <ignore>/etc/mail/statistics</ignore>
        <ignore>/etc/random-seed</ignore>
        <ignore>/etc/random.seed</ignore>
        <ignore>/etc/adjtime</ignore>
        <ignore>/etc/httpd/logs</ignore>
        <ignore>/etc/utmpx</ignore>
        <ignore>/etc/wtmpx</ignore>
        <ignore>/etc/cups/certs</ignore>
        <ignore>/etc/dumpdates</ignore>
        <ignore>/etc/svc/volatile</ignore>

        <!-- Files/directories to ignore in the docker container mounted path -->
        <ignore>/opt/hostexport/etc/mtab</ignore>
        <ignore>/opt/hostexport/etc/hosts.deny</ignore>
        <ignore>/opt/hostexport/etc/mail/statistics</ignore>
        <ignore>/opt/hostexport/etc/random-seed</ignore>
        <ignore>/opt/hostexport/etc/random.seed</ignore>
        <ignore>/opt/hostexport/etc/adjtime</ignore>
        <ignore>/opt/hostexport/etc/httpd/logs</ignore>
        <ignore>/opt/hostexport/etc/utmpx</ignore>
        <ignore>/opt/hostexport/etc/wtmpx</ignore>
        <ignore>/opt/hostexport/etc/cups/certs</ignore>
        <ignore>/opt/hostexport/etc/dumpdates</ignore>
        <ignore>/opt/hostexport/etc/svc/volatile</ignore>

        <!-- Check the file, but never compute the diff -->
        <nodiff>/etc/ssl/private.key</nodiff>

        <!-- Check the file, but never compute the diff in the docker container mounted path -->
        <nodiff>/opt/hostexport/etc/ssl/private.key</nodiff>

        <skip_nfs>yes</skip_nfs>
      </syscheck>

      <!-- Log analysis -->
      <localfile>
        <log_format>syslog</log_format>
        <location>/var/ossec/logs/active-responses.log</location>
      </localfile>

      <localfile>
        <log_format>syslog</log_format>
        <location>/var/log/dpkg.log</location>
      </localfile>

      <localfile>
        <log_format>docker-logs</log_format>
        <location>/var/lib/docker/containers/*</location>
      </localfile>

      <localfile>
        <log_format>command</log_format>
        <command>df -P</command>
        <frequency>360</frequency>
      </localfile>

      <localfile>
        <log_format>full_command</log_format>
        <command>netstat -tulpn | sed 's/\([[:alnum:]]\+\)\ \+[[:digit:]]\+\ \+[[:digit:]]\+\ \+\(.*\):\([[:digit:]]*\)\ \+\([0-9\.\:\*]\+\).\+\ \([[:digit:]]*\/[[:alnum:]\-]*\).*/\1 \2 == \3 == \4 \5/' | sort -k 4 -g | sed 's/ == \(.*\) ==/:\1/' | sed 1,2d</command>
        <alias>netstat listening ports</alias>
        <frequency>360</frequency>
      </localfile>

      <localfile>
        <log_format>full_command</log_format>
        <command>last -n 20</command>
        <frequency>360</frequency>
      </localfile>

      <!-- Active response -->
      <active-response>
        <disabled>no</disabled>
        <ca_store>/var/ossec/etc/wpk_root.pem</ca_store>
      </active-response>

      <!-- Choose between "plain", "json", or "plain,json" for the format of internal logs -->
      <logging>
        <log_format>plain</log_format>
      </logging>

    </ossec_config>
