---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: wazuh-agent
  namespace: wazuh
  labels:
    app: wazuh-agent
spec:
  selector:
    matchLabels:
      app: wazuh-agent
  template:
    metadata:
      labels:
        app: wazuh-agent
    spec:
      containers:
      - name: wazuh-agent
        image: garland/wazuh-agent:3.2.4
        imagePullPolicy: Always
        command: ["/bin/bash"]
        args: ["-c",
                "/var/ossec/bin/agent-auth -m wazuh-manager -p 1515; /var/ossec/bin/ossec-control start; tail -f /var/ossec/logs/*.log;"
                ]
        # env:
        #   - name: GRAVITEE_MANAGEMENT_MONGODB_URI
        #     value: "mongodb://mongodb-gravitee:27017/gravitee?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000"
        #   - name: gravitee_ratelimit_mongodb_uri
        #     value: "mongodb://mongodb-gravitee:27017/gravitee?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000"
        #   - name: gravitee_reporters_elasticsearch_endpoints_0
        #     value: http://elasticsearch-logging:9200
        # ports:
        # - containerPort: 8082
        # resources:
        #   requests:
        #     memory: "256Mi"
        #     cpu: "250m"
        #   limits:
        #     memory: "1024Mi"
        #     cpu: "500m"
        volumeMounts:
        - name: hostexport-varlog
          mountPath: /opt/var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: hostexport-etc
          mountPath: /opt/hostexport/etc
          readOnly: true
        - name: hostexport-usr-bin
          mountPath: /opt/hostexport/usr/bin
          readOnly: true
        - name: hostexport-usr-sbin
          mountPath: /opt/hostexport/usr/sbin
          readOnly: true
        - name: hostexport-bin
          mountPath: /opt/hostexport/bin
          readOnly: true
        - name: hostexport-sbin
          mountPath: /opt/hostexport/sbin
          readOnly: true
        - name: hostexport-boot
          mountPath: /opt/hostexport/boot
          readOnly: true
      volumes:
      - name: hostexport-varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: hostexport-etc
        hostPath:
          path: /etc
      - name: hostexport-usr-bin
        hostPath:
          path: /usr/bin
      - name: hostexport-usr-sbin
        hostPath:
          path: /usr/sbin
      - name: hostexport-bin
        hostPath:
          path: /bin
      - name: hostexport-sbin
        hostPath:
          path: /sbin
      - name: hostexport-boot
        hostPath:
          path: /boot
