---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: wazuh-agent
  namespace: wazuh
  labels:
    app: wazuh-agent
spec:
  selector:
    matchLabels:
      app: wazuh-agent
  template:
    metadata:
      labels:
        app: wazuh-agent
    spec:
      containers:
      - name: wazuh-agent
        image: garland/wazuh-agent:3.2.4
        imagePullPolicy: Always
        command: ["/bin/bash"]
        args: ["-c",
                "/var/ossec/bin/agent-auth -m wazuh-manager-master-0.wazuh-master.wazuh.svc.cluster.local -p 1515; /var/ossec/bin/ossec-control start; tail -f /var/ossec/logs/*.log;"
                ]
        # env:
        #   - name: GRAVITEE_MANAGEMENT_MONGODB_URI
        #     value: "mongodb://mongodb-gravitee:27017/gravitee?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000"
        #   - name: gravitee_ratelimit_mongodb_uri
        #     value: "mongodb://mongodb-gravitee:27017/gravitee?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000"
        #   - name: gravitee_reporters_elasticsearch_endpoints_0
        #     value: http://elasticsearch-logging:9200
        # ports:
        # - containerPort: 8082
        # resources:
        #   requests:
        #     memory: "256Mi"
        #     cpu: "250m"
        #   limits:
        #     memory: "1024Mi"
        #     cpu: "500m"
